name: Publish PowerDNS plugin for Certbot Python Package

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: python -m build
      
    - name: Determine release type
      id: release-type
      run: |
        if [[ ${{ github.event.release.prerelease }} == true ]]; then
          echo "target=testpypi" >> $GITHUB_OUTPUT
        else
          echo "target=pypi" >> $GITHUB_OUTPUT
        fi
        
    - name: Upload to TestPyPI (pre-releases)
      if: steps.release-type.outputs.target == 'testpypi'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        
    - name: Upload to PyPI (releases)
      if: steps.release-type.outputs.target == 'pypi'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
